-- ============================================================================
-- OWASP Amass: Complete DDL Script (PostgreSQL 13+)
-- Source: github.com/owasp-amass/asset-db@v0.24.2
--
-- Dependency order:
--   1. Extensions
--   2. Lookup tables + seed data
--   3. Core graph tables (entity, edge, entity_tag, edge_tag)
--   4. Asset tables (21 tables)
--
-- Does NOT include PL/pgSQL functions (see functions.sql)
-- ============================================================================

-- ============================================================================
-- 1. EXTENSIONS
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

-- ============================================================================
-- 2. LOOKUP TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.entity_type_lu (
  id   smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text UNIQUE NOT NULL
);
CREATE UNIQUE INDEX entity_type_lu_name_lower_uidx ON public.entity_type_lu (lower(name));

CREATE TABLE IF NOT EXISTS public.edge_type_lu (
  id   smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text UNIQUE NOT NULL
);
CREATE UNIQUE INDEX edge_type_lu_name_lower_uidx ON public.edge_type_lu (lower(name));

CREATE TABLE IF NOT EXISTS public.tag_type_lu (
  id    smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name  text NOT NULL UNIQUE
);
CREATE UNIQUE INDEX tag_type_lu_name_lower_uidx ON public.tag_type_lu (lower(name));

-- Seed data
INSERT INTO public.entity_type_lu(name) VALUES
  ('account'),('autnumrecord'),('autonomoussystem'),('contactrecord'),('domainrecord'),('file'),
  ('fqdn'),('fundstransfer'),('identifier'),('ipaddress'),('ipnetrecord'),('location'),('netblock'),
  ('organization'),('person'),('phone'),('product'),('productrelease'),('service'),('tlscertificate'),
  ('url')
ON CONFLICT DO NOTHING;

INSERT INTO public.edge_type_lu(name) VALUES
  ('basicdnsrelation'),('portrelation'),('prefdnsrelation'),('simplerelation'),('srvdnsrelation')
ON CONFLICT DO NOTHING;

INSERT INTO public.tag_type_lu(name) VALUES
  ('dnsrecordproperty'),('simpleproperty'),('sourceproperty'),('vulnproperty')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- 3. CORE GRAPH TABLES
-- ============================================================================

-- Entity mapping
CREATE TABLE IF NOT EXISTS public.entity (
  entity_id     bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at    timestamp without time zone NOT NULL DEFAULT now(),
  updated_at    timestamp without time zone NOT NULL DEFAULT now(),
  etype_id      smallint  NOT NULL REFERENCES public.entity_type_lu(id),
  natural_key   citext    NOT NULL,
  table_name    citext    NOT NULL,
  row_id        bigint    NOT NULL,
  UNIQUE (etype_id, row_id),
  UNIQUE (etype_id, natural_key),
  UNIQUE (table_name, row_id)
);
CREATE INDEX IF NOT EXISTS idx_entity_created_at ON public.entity (created_at);
CREATE INDEX IF NOT EXISTS idx_entity_updated_at ON public.entity (updated_at);

-- Graph edges
CREATE TABLE IF NOT EXISTS public.edge (
  edge_id        bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at     timestamp without time zone NOT NULL DEFAULT now(),
  updated_at     timestamp without time zone NOT NULL DEFAULT now(),
  etype_id       smallint    NOT NULL REFERENCES public.edge_type_lu(id),
  label          citext      NOT NULL,
  content        jsonb       NOT NULL DEFAULT '{}'::jsonb,
  from_entity_id bigint      NOT NULL REFERENCES public.entity(entity_id) ON DELETE CASCADE,
  to_entity_id   bigint      NOT NULL REFERENCES public.entity(entity_id) ON DELETE CASCADE,
  UNIQUE (etype_id, from_entity_id, to_entity_id, label),
  CHECK (from_entity_id <> to_entity_id)
);
CREATE INDEX IF NOT EXISTS idx_edge_created_at ON public.edge (created_at);
CREATE INDEX IF NOT EXISTS idx_edge_updated_at ON public.edge (updated_at);
CREATE INDEX IF NOT EXISTS idx_edge_etype ON public.edge (etype_id);
CREATE INDEX IF NOT EXISTS gin_edge_content ON public.edge USING gin (content jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_edge_from_id ON public.edge (from_entity_id);
CREATE INDEX IF NOT EXISTS idx_edge_to_id   ON public.edge (to_entity_id);
CREATE INDEX IF NOT EXISTS idx_edge_from ON public.edge (from_entity_id, etype_id, to_entity_id);
CREATE INDEX IF NOT EXISTS idx_edge_to   ON public.edge (to_entity_id, etype_id, from_entity_id);

-- Entity tags
CREATE TABLE IF NOT EXISTS public.entity_tag (
  tag_id          bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at      timestamp without time zone NOT NULL DEFAULT now(),
  updated_at      timestamp without time zone NOT NULL DEFAULT now(),
  entity_id       bigint NOT NULL REFERENCES public.entity(entity_id) ON DELETE CASCADE,
  ttype_id        smallint NOT NULL REFERENCES public.tag_type_lu(id),
  property_name   TEXT NOT NULL,
  property_value  TEXT NOT NULL,
  content         jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (entity_id, ttype_id, property_name, property_value)
);
CREATE INDEX IF NOT EXISTS idx_entity_tag_created_at ON public.entity_tag (created_at);
CREATE INDEX IF NOT EXISTS idx_entity_tag_updated_at ON public.entity_tag (updated_at);
CREATE INDEX IF NOT EXISTS idx_entity_tag_entity_updated
  ON public.entity_tag (entity_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_entity_tag_entity_id ON public.entity_tag (entity_id);
CREATE INDEX IF NOT EXISTS idx_entity_tag_ttype_id ON public.entity_tag (ttype_id);
CREATE INDEX IF NOT EXISTS idx_entity_tag_property_name ON public.entity_tag (property_name);
CREATE INDEX IF NOT EXISTS idx_entity_tag_tt_name ON public.entity_tag (ttype_id, property_name);
CREATE INDEX IF NOT EXISTS idx_entity_tag_property_name_value
  ON public.entity_tag (property_name, property_value);
CREATE INDEX IF NOT EXISTS idx_entity_tag_ttype_name_value
  ON public.entity_tag (ttype_id, property_name, property_value);
CREATE INDEX IF NOT EXISTS gin_entity_tag_content ON public.entity_tag USING gin (content jsonb_path_ops);

-- Edge tags
CREATE TABLE IF NOT EXISTS public.edge_tag (
  tag_id          bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at      timestamp without time zone NOT NULL DEFAULT now(),
  updated_at      timestamp without time zone NOT NULL DEFAULT now(),
  edge_id         bigint NOT NULL REFERENCES public.edge(edge_id) ON DELETE CASCADE,
  ttype_id        smallint NOT NULL REFERENCES public.tag_type_lu(id),
  property_name   TEXT NOT NULL,
  property_value  TEXT NOT NULL,
  content         jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (edge_id, ttype_id, property_name, property_value)
);
CREATE INDEX IF NOT EXISTS idx_edge_tag_created_at ON public.edge_tag (created_at);
CREATE INDEX IF NOT EXISTS idx_edge_tag_updated_at ON public.edge_tag (updated_at);
CREATE INDEX IF NOT EXISTS idx_edge_tag_edge_updated ON public.edge_tag (edge_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_edge_tag_edge_id ON public.edge_tag (edge_id);
CREATE INDEX IF NOT EXISTS idx_edge_tag_ttype_id ON public.edge_tag (ttype_id);
CREATE INDEX IF NOT EXISTS idx_edge_tag_property_name ON public.edge_tag (property_name);
CREATE INDEX IF NOT EXISTS idx_edge_tag_tt_name ON public.edge_tag (ttype_id, property_name);
CREATE INDEX IF NOT EXISTS idx_edge_tag_property_name_value
  ON public.edge_tag (property_name, property_value);
CREATE INDEX IF NOT EXISTS idx_edge_tag_ttype_name_value
  ON public.edge_tag (ttype_id, property_name, property_value);
CREATE INDEX IF NOT EXISTS gin_edge_tag_content ON public.edge_tag USING gin (content jsonb_path_ops);

-- ============================================================================
-- 4. ASSET TABLES
-- ============================================================================

-- account
CREATE TABLE IF NOT EXISTS public.account (
  id             bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at     timestamp without time zone NOT NULL DEFAULT now(),
  updated_at     timestamp without time zone NOT NULL DEFAULT now(),
  unique_id      text NOT NULL UNIQUE,
  account_type   text NOT NULL,
  username       text,
  account_number text,
  attrs          jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_account_created_at ON public.account (created_at);
CREATE INDEX IF NOT EXISTS idx_account_updated_at_id_desc ON public.account (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_account_account_type ON public.account (account_type);
CREATE INDEX IF NOT EXISTS idx_account_username ON public.account (username);
CREATE INDEX IF NOT EXISTS idx_account_account_number ON public.account (account_number);

-- autnumrecord
CREATE TABLE IF NOT EXISTS public.autnumrecord (
  id           bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at   timestamp without time zone NOT NULL DEFAULT now(),
  updated_at   timestamp without time zone NOT NULL DEFAULT now(),
  handle       text NOT NULL UNIQUE,
  asn          integer NOT NULL UNIQUE,
  record_name  text,
  whois_server citext,
  attrs        jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_autnumrecord_created_at ON public.autnumrecord (created_at);
CREATE INDEX IF NOT EXISTS idx_autnumrecord_updated_at_id_desc ON public.autnumrecord (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_autnumrecord_name ON public.autnumrecord (record_name);
CREATE INDEX IF NOT EXISTS idx_autnumrecord_whois_server ON public.autnumrecord (whois_server);

-- autonomoussystem
CREATE TABLE IF NOT EXISTS public.autonomoussystem (
  id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  asn        integer NOT NULL UNIQUE,
  attrs      jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_autonomoussystem_created_at ON public.autonomoussystem (created_at);
CREATE INDEX IF NOT EXISTS idx_autonomoussystem_updated_at_id_desc ON public.autonomoussystem (updated_at DESC, id DESC);

-- contactrecord
CREATE TABLE IF NOT EXISTS public.contactrecord (
  id            bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at    timestamp without time zone NOT NULL DEFAULT now(),
  updated_at    timestamp without time zone NOT NULL DEFAULT now(),
  discovered_at text NOT NULL UNIQUE,
  attrs         jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_contactrecord_created_at ON public.contactrecord (created_at);
CREATE INDEX IF NOT EXISTS idx_contactrecord_updated_at_id_desc ON public.contactrecord (updated_at DESC, id DESC);

-- domainrecord
CREATE TABLE IF NOT EXISTS public.domainrecord (
  id              bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at      timestamp without time zone NOT NULL DEFAULT now(),
  updated_at      timestamp without time zone NOT NULL DEFAULT now(),
  domain          citext NOT NULL UNIQUE,
  record_name     text,
  punycode        text,
  extension       text,
  whois_server    citext,
  object_id       text,
  attrs           jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_domainrecord_created_at ON public.domainrecord (created_at);
CREATE INDEX IF NOT EXISTS idx_domainrecord_updated_at_id_desc ON public.domainrecord (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_domainrecord_name ON public.domainrecord (record_name);
CREATE INDEX IF NOT EXISTS idx_domainrecord_extension ON public.domainrecord (extension);
CREATE INDEX IF NOT EXISTS idx_domainrecord_punycode ON public.domainrecord (punycode);
CREATE INDEX IF NOT EXISTS idx_domainrecord_whois_server ON public.domainrecord (whois_server);
CREATE INDEX IF NOT EXISTS idx_domainrecord_object_id ON public.domainrecord (object_id);

-- file
CREATE TABLE IF NOT EXISTS public.file (
  id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  file_url   text NOT NULL UNIQUE,
  basename   text,
  file_type  text,
  attrs      jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_file_created_at ON public.file (created_at);
CREATE INDEX IF NOT EXISTS idx_file_updated_at_id_desc ON public.file (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_file_basename ON public.file (basename);
CREATE INDEX IF NOT EXISTS idx_file_file_type ON public.file (file_type);

-- fqdn
CREATE TABLE IF NOT EXISTS public.fqdn (
  id           bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at   timestamp without time zone NOT NULL DEFAULT now(),
  updated_at   timestamp without time zone NOT NULL DEFAULT now(),
  fqdn         citext NOT NULL UNIQUE,
  reverse_fqdn text COLLATE pg_catalog."default" GENERATED ALWAYS AS (reverse((fqdn)::text)) STORED,
  attrs        jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_fqdn_created_at ON public.fqdn (created_at);
CREATE INDEX IF NOT EXISTS idx_fqdn_updated_at_id_desc ON public.fqdn (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_fqdn_reverse_fqdn ON public.fqdn USING btree
  (reverse_fqdn COLLATE pg_catalog."default" text_pattern_ops ASC NULLS LAST)
  WITH (fillfactor=100, deduplicate_items=True)
  TABLESPACE pg_default;

-- fundstransfer
CREATE TABLE IF NOT EXISTS public.fundstransfer (
  id               bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at       timestamp without time zone NOT NULL DEFAULT now(),
  updated_at       timestamp without time zone NOT NULL DEFAULT now(),
  unique_id        text NOT NULL UNIQUE,
  amount           numeric NOT NULL,
  reference_number text,
  attrs            jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_fundstransfer_created_at ON public.fundstransfer (created_at);
CREATE INDEX IF NOT EXISTS idx_fundstransfer_updated_at_id_desc ON public.fundstransfer (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_fundstransfer_amount ON public.fundstransfer (amount);
CREATE INDEX IF NOT EXISTS idx_fundstransfer_reference_number ON public.fundstransfer (reference_number);

-- identifier
CREATE TABLE IF NOT EXISTS public.identifier (
  id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  unique_id  text NOT NULL UNIQUE,
  id_value   text NOT NULL,
  id_type    text NOT NULL,
  attrs      jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(id_value, id_type)
);
CREATE INDEX IF NOT EXISTS idx_identifier_created_at ON public.identifier (created_at);
CREATE INDEX IF NOT EXISTS idx_identifier_updated_at_id_desc ON public.identifier (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_identifier_id_value ON public.identifier (id_value);
CREATE INDEX IF NOT EXISTS idx_identifier_id_type ON public.identifier (id_type);

-- ipaddress
CREATE TABLE IF NOT EXISTS public.ipaddress (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  ip_address inet NOT NULL UNIQUE,
  attrs      jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_ipaddress_created_at ON public.ipaddress (created_at);
CREATE INDEX IF NOT EXISTS idx_ipaddress_updated_at_id_desc ON public.ipaddress (updated_at DESC, id DESC);

-- ipnetrecord
CREATE TABLE IF NOT EXISTS public.ipnetrecord (
  id            bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at    timestamp without time zone NOT NULL DEFAULT now(),
  updated_at    timestamp without time zone NOT NULL DEFAULT now(),
  record_cidr   cidr NOT NULL UNIQUE,
  record_name   text NOT NULL,
  handle        text NOT NULL UNIQUE,
  whois_server  citext,
  parent_handle text,
  start_address inet,
  end_address   inet,
  attrs         jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_ipnetrecord_created_at ON public.ipnetrecord (created_at);
CREATE INDEX IF NOT EXISTS idx_ipnetrecord_updated_at_id_desc ON public.ipnetrecord (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_ipnetrecord_name ON public.ipnetrecord (record_name);
CREATE INDEX IF NOT EXISTS idx_ipnetrecord_start_address ON public.ipnetrecord (start_address);
CREATE INDEX IF NOT EXISTS idx_ipnetrecord_end_address ON public.ipnetrecord (end_address);
CREATE INDEX IF NOT EXISTS idx_ipnetrecord_whois_server ON public.ipnetrecord (whois_server);
CREATE INDEX IF NOT EXISTS idx_ipnetrecord_parent_handle ON public.ipnetrecord (parent_handle);

-- location
CREATE TABLE IF NOT EXISTS public.location (
  id              bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at      timestamp without time zone NOT NULL DEFAULT now(),
  updated_at      timestamp without time zone NOT NULL DEFAULT now(),
  street_address  text NOT NULL UNIQUE,
  city            text NOT NULL,
  country         text NOT NULL,
  unit            text,
  building        text,
  province        text,
  locality        text,
  postal_code     text,
  street_name     text,
  building_number text,
  attrs           jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_location_created_at ON public.location (created_at);
CREATE INDEX IF NOT EXISTS idx_location_updated_at_id_desc ON public.location (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_location_building ON public.location (building);
CREATE INDEX IF NOT EXISTS idx_location_building_number ON public.location (building_number);
CREATE INDEX IF NOT EXISTS idx_location_province ON public.location (province);
CREATE INDEX IF NOT EXISTS idx_location_street_name ON public.location (street_name);
CREATE INDEX IF NOT EXISTS idx_location_unit ON public.location (unit);
CREATE INDEX IF NOT EXISTS idx_location_locality ON public.location (locality);
CREATE INDEX IF NOT EXISTS idx_location_city ON public.location (city);
CREATE INDEX IF NOT EXISTS idx_location_country ON public.location (country);
CREATE INDEX IF NOT EXISTS idx_location_postal_code ON public.location (postal_code);

-- netblock
CREATE TABLE IF NOT EXISTS public.netblock (
  id            bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at    timestamp without time zone NOT NULL DEFAULT now(),
  updated_at    timestamp without time zone NOT NULL DEFAULT now(),
  netblock_cidr cidr NOT NULL UNIQUE,
  attrs         jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_netblock_created_at ON public.netblock (created_at);
CREATE INDEX IF NOT EXISTS idx_netblock_updated_at_id_desc ON public.netblock (updated_at DESC, id DESC);

-- organization
CREATE TABLE IF NOT EXISTS public.organization (
  id              bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at      timestamp without time zone NOT NULL DEFAULT now(),
  updated_at      timestamp without time zone NOT NULL DEFAULT now(),
  unique_id       text NOT NULL UNIQUE,
  org_name        text NOT NULL,
  legal_name      text,
  jurisdiction    text,
  registration_id text,
  attrs           jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_organization_created_at ON public.organization (created_at);
CREATE INDEX IF NOT EXISTS idx_organization_updated_at_id_desc ON public.organization (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_organization_org_name ON public.organization (org_name);
CREATE INDEX IF NOT EXISTS idx_organization_legal_name ON public.organization (legal_name);
CREATE INDEX IF NOT EXISTS idx_organization_jurisdiction ON public.organization (jurisdiction);
CREATE INDEX IF NOT EXISTS idx_organization_registration_id ON public.organization (registration_id);

-- person
CREATE TABLE IF NOT EXISTS public.person (
  id          bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at  timestamp without time zone NOT NULL DEFAULT now(),
  updated_at  timestamp without time zone NOT NULL DEFAULT now(),
  unique_id   text NOT NULL UNIQUE,
  full_name   text,
  first_name  text,
  family_name text,
  attrs       jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_person_created_at ON public.person (created_at);
CREATE INDEX IF NOT EXISTS idx_person_updated_at_id_desc ON public.person (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_person_full_name ON public.person (full_name);
CREATE INDEX IF NOT EXISTS idx_person_first_name ON public.person (first_name);
CREATE INDEX IF NOT EXISTS idx_person_family_name ON public.person (family_name);

-- phone
CREATE TABLE IF NOT EXISTS public.phone (
    id           bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at   timestamp without time zone NOT NULL DEFAULT now(),
    updated_at   timestamp without time zone NOT NULL DEFAULT now(),
    e164         text NOT NULL UNIQUE,
    country_code integer,
    attrs        jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_phone_created_at ON public.phone (created_at);
CREATE INDEX IF NOT EXISTS idx_phone_updated_at_id_desc ON public.phone (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_phone_country_code ON public.phone (country_code);

-- product
CREATE TABLE IF NOT EXISTS public.product (
  id           bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at   timestamp without time zone NOT NULL DEFAULT now(),
  updated_at   timestamp without time zone NOT NULL DEFAULT now(),
  unique_id    text NOT NULL UNIQUE,
  product_name text NOT NULL,
  product_type text NOT NULL,
  attrs        jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_product_created_at ON public.product (created_at);
CREATE INDEX IF NOT EXISTS idx_product_updated_at_id_desc ON public.product (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_product_name ON public.product (product_name);
CREATE INDEX IF NOT EXISTS idx_product_type ON public.product (product_type);

-- productrelease
CREATE TABLE IF NOT EXISTS public.productrelease (
  id           bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at   timestamp without time zone NOT NULL DEFAULT now(),
  updated_at   timestamp without time zone NOT NULL DEFAULT now(),
  release_name text NOT NULL UNIQUE,
  attrs        jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_productrelease_created_at ON public.productrelease (created_at);
CREATE INDEX IF NOT EXISTS idx_productrelease_updated_at_id_desc ON public.productrelease (updated_at DESC, id DESC);

-- service
CREATE TABLE IF NOT EXISTS public.service (
  id           bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at   timestamp without time zone NOT NULL DEFAULT now(),
  updated_at   timestamp without time zone NOT NULL DEFAULT now(),
  unique_id    text NOT NULL UNIQUE,
  service_type text NOT NULL,
  attrs        jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_service_created_at ON public.service (created_at);
CREATE INDEX IF NOT EXISTS idx_service_updated_at_id_desc ON public.service (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_service_service_type ON public.service (service_type);

-- tlscertificate
CREATE TABLE IF NOT EXISTS public.tlscertificate (
  id                  bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at          timestamp without time zone NOT NULL DEFAULT now(),
  updated_at          timestamp without time zone NOT NULL DEFAULT now(),
  serial_number       text NOT NULL UNIQUE,
  subject_common_name text NOT NULL,
  attrs               jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_tlscertificate_created_at ON public.tlscertificate (created_at);
CREATE INDEX IF NOT EXISTS idx_tlscertificate_updated_at_id_desc ON public.tlscertificate (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_tlscertificate_subject_common_name ON public.tlscertificate (subject_common_name);

-- url
CREATE TABLE IF NOT EXISTS public.url (
  id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  raw_url    text NOT NULL UNIQUE,
  scheme     text,
  attrs      jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_url_created_at ON public.url (created_at);
CREATE INDEX IF NOT EXISTS idx_url_updated_at_id_desc ON public.url (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_url_scheme ON public.url (scheme);
