apiVersion: v1
kind: Service
metadata:
  name: {{ include "amass-conductor.fullname" . }}
  {{- if .Values.tailscale.enabled }}
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: {{ .Values.tailscale.hostname | quote }}
    tailscale.com/tags: {{ .Values.tailscale.tags | quote }}
  {{- end }}
  labels:
    {{- include "amass-conductor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "amass-conductor.selectorLabels" . | nindent 4 }}
