<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AmassOrchestrator.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
    <PackageReference Include="Radzen.Blazor" Version="9.0.8" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wordlists\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="wordlists\*.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Exclude files in the App_Data folder and any .log files from being watched -->
    <DefaultItemExcludes>$(DefaultItemExcludes);App_Data\**;**\*.log</DefaultItemExcludes>
  </PropertyGroup>

</Project>
