<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AmassOrchestrator.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
    <PackageReference Include="Radzen.Blazor" Version="9.0.8" />
  </ItemGroup>

</Project>
